# For documentation about OSS Review Toolkit see https://github.com/oss-review-toolkit/ort

name: 'OSO OSS Review Toolkit'
description: >
  A Github Action for the OSS Review Toolkit (https://github.com/oss-review-toolkit/ort).

  The following reports are generated
  - ort/analyzer-result.yml

inputs:
  ort-aws-access-key-id:
    description: AWS access key id for the AWS ECR where the ORT container is located
    required: true
  ort-aws-secret-access-key:
    description: AWS access key for the AWS ECR where the ORT container is located
    required: true
  project-dir:
    description: Directory where the source code is located and the reports are saved in the `ort` subfolder
    required: false
    default: $GITHUB_WORKSPACE/
  container-registry:
    description: Registry for ORT docker container
    required: true
  container-repository:
    description: Repository for ORT docker container
    required: true
  container-image-tag:
    description: Image tag for ORT docker container
    required: false
    default: latest
  allow-dynamic-versions:
    description: |
      Set to 'true' only if dynamic dependency versions are allowed (note version ranges specified for dependencies may cause unstable results).
      This field applies only to package managers that support lock files, e.g. NPM.
    required: false
    default: 'false'
    
runs:
  using: composite
  steps:
    # Configure AWS credentials
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.ort-aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.ort-aws-secret-access-key }}
        aws-region: eu-central-1

    # Login to ORT Amazon ECR
    - uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: true

    - name: Pull OSO ORT Image
      shell: bash
      run: |
        docker pull ${{ inputs.container-registry }}/${{ inputs.container-repository }}:${{ inputs.container-image-tag }}

    - name: Initialize ORT workspace
      shell: bash
      run: |
        mkdir -p $HOME/.cache/scancode-tk/; chmod -R aug+w ${HOME}/.cache/ || :
        mkdir -p $HOME/.config/jgit/; chmod -R aug+w ${HOME}/.config/ || :
        mkdir -p $HOME/.ort/{cache,config,ort-results,scanner/archive/,scanner/provenance/}; chmod -R aug+w ${HOME}/.ort/ || :
        mkdir -p $HOME/.gradle/; chmod -R aug+w ${HOME}/.gradle/ || :
        mkdir -p $HOME/.rustup/{cache,download,tmp}; chmod -R aug+w ${HOME}/.rustup/ || :
        mkdir -p $HOME/go/; chmod -R aug+w ${HOME}/go/ || :
        container_id=$(docker create ${{ inputs.container-registry }}/${{ inputs.container-repository }}:${{ inputs.container-image-tag }}) || :
        docker cp $container_id:/home/ort/curations/ $HOME/curations || :
        docker cp $container_id:/home/ort/.ort/config/config.yml $HOME/.ort/config/config.yml || :
        docker rm $container_id || :

    # https://github.com/oss-review-toolkit/ort#analyzer
    - name: ORT Analyzer
      continue-on-error: true
      shell: bash
      run: |
        docker run \
          --mount type=bind,source=$HOME,target=/home/ort \
          -v ${{ inputs.project-dir }}:/project \
          -u $(id -u):$(id -g) \
          ${{ inputs.container-registry }}/${{ inputs.container-repository }}:${{ inputs.container-image-tag }} \
          -P ort.analyzer.allowDynamicVersions=${{ inputs.allow-dynamic-versions }} \
          analyze \
          --input-dir /project/ \
          --output-dir /project/ort/

    # Archive ORT YAML result
    - uses: actions/upload-artifact@v4
      with:
        name: ort-analyzer-result
        path: ort/analyzer-result.yml
